# Configuration: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: false
version: 2.1
contact_links:
  - name: Discord
    url: https://discord.gg/pMNeuGrDky
    about: General usage questions and community discussions
