name: PY SDK CI

on:
  pull_request:
    paths:
      - 'sdk/embedbase-py/**'
  push:
    branches:
      - main
      - next
      - rc
    paths:
      - 'sdk/embedbase-py/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: make poetry-download
      working-directory: sdk/embedbase-py

    - name: Set up cache
      uses: actions/cache@v2.1.6
      with:
        path: sdk/embedbase-py/.venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('sdk/embedbase-py/pyproject.toml') }}-${{ hashFiles('sdk/embedbase-py/poetry.lock') }}
    
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install
      working-directory: sdk/embedbase-py

    - name: Run tests
      run: |
        make test
      working-directory: sdk/embedbase-py
