name: Test & Release if needed

on:
  push:
    branches:
      - main
      - next
      - rc
    paths:
      - 'embedbase/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^Release ([^ ]+)'

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(python3 setup.py --version)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist
          twine upload dist/*

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Embedbase production with minimal dependencies
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: FLAVOR=minimal
          tags: |
            ghcr.io/${{ github.repository_owner }}/embedbase:${{ env.VERSION }}-minimal

      - name: Build and push dev
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.dev
          platforms: linux/amd64
          push: true
          build-args: FLAVOR=all
          tags: |
            ghcr.io/${{ github.repository_owner }}/embedbase:latest-dev

      - name: Build and push Embedbase production with full dependencies
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: FLAVOR=all
          tags: |
            ghcr.io/${{ github.repository_owner }}/embedbase:${{ env.VERSION }}-all
            ghcr.io/${{ github.repository_owner }}/embedbase:latest
      
      - name: Create Release
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
